#!/bin/bash -l
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --sockets-per-node=2
#SBATCH --mem=10G
#SBATCH --job-name=mcr
#SBATCH --output=JOB.o
#SBATCH --error=JOB.e

export PW=/home/software/materia/qe-6.7.0/bin/pw.x

source /home/software/materia/intel_lib/setvars.sh --force
export I_MPI_PMI_LIBRARY=/usr/lib/x86_64-linux-gnu/libpmi2.so.0
export I_MPI_FABRICS=shm:dapl

ecut="35"
celldim="7.2447"
k_points=" 3 4 5 "
ecut8=`awk 'BEGIN {print 8*'$ecut'}' `

for i in $k_points
do

FILE=k_points_0$i

cat > $FILE.pwi << EOF
 &control
    calculation = 'scf'
    restart_mode = 'from_scratch'
    verbosity = 'default'
    prefix = Rh_bulk
    pseudo_dir = '/home/software/materia/pseudo',
    outdir = '/home/STUDENTI/leonardo.razzai/WORK/k_points'
    disk_io = 'nowf'
 /
 &system    
    ibrav = 2
    celldm(1) = $celldim
    nat = 1
    ntyp = 1
    ecutwfc = $ecut 
    ecutrho = $ecut8
    nspin = 2
    starting_magnetization(1) = 0.01
    occupations = 'smearing'
    smearing = 'gaussian'
    degauss = 0.02
 /
 &electrons
    diagonalization = 'david'
    electron_maxstep = 200
    mixing_mode = 'plain'
    mixing_beta = 0.40
    conv_thr = 1.0d-6
/

ATOMIC_SPECIES
Rh      102.905    rh_pbe_v1.4.uspp.F.UPF

ATOMIC_POSITIONS angstrom
Rh   0.00   0.00   0.00

K_POINTS automatic
$i $i $i   1 1 1

EOF

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# running

cd $SLURM_SUBMIT_DIR
srun --cpu-bind=core $PW  -input  $FILE.pwi >> $FILE.pwo

done
