#!/bin/bash -l
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --mem=64G
#SBATCH --constraint=ib          
#SBATCH --ntasks-per-node=16
#SBATCH --sockets-per-node=2
#SBATCH --partition=b1,b2,b3,b4,b5,m1,m2
#SBATCH --job-name=@_@
#SBATCH --output=JOB.o

module load materia/qe/7.1_openmpi

FILE=Rh_bulk

cat > $FILE.pwi << EOF
&CONTROL
    calculation = 'relax'
    restart_mode = 'from_scratch'
    pseudo_dir = '/home/software/materia/pseudo'
    outdir = '/home/STUDENTI/leonardo.razzai/Rh_work/surf_111'
    prefix = 'Rh111_bulk'
    disk_io = 'nowf'
    max_seconds = 36000
/
&SYSTEM
    ibrav = 4
    celldm(1) = 5.122776
    celldm(3) = 2.449490
    nat = 3
    ntyp = 1
    ecutwfc = 35
    ecutrho = 280
    nspin = 2
    starting_magnetization(1) = 0.01
    occupations = 'smearing'
    smearing = 'gaussian'
    degauss = 0.02
/
&ELECTRONS
    diagonalization = 'david'
    electron_maxstep = 200
    mixing_mode = 'local-TF'
    mixing_beta = 0.40
    conv_thr = 1.0d-6
/
&IONS
    ion_dynamics = 'bfgs'
    upscale = 10
/

ATOMIC_SPECIES
Rh      102.905    rh_pbe_v1.4.uspp.F.UPF 

ATOMIC_POSITIONS angstrom
Rh   0.0000000   0.0000000   0.0000000
Rh   1.3554284   -0.7825569   2.2134053
Rh   1.3554284   0.7825569   4.4268106

K_POINTS automatic
9 9 4 1 1 1

EOF

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# running

srun -n 16 pw.x -nk 1 -input $FILE.pwi > $FILE.pwo
