#!/bin/bash -l
#SBATCH --time=20:00:00
#SBATCH --nodes=1
#SBATCH --mem=64G
#SBATCH --constraint=ib          
#SBATCH --ntasks-per-node=56
#SBATCH --sockets-per-node=2
#SBATCH --partition=m1,m3
#SBATCH --job-name=COO
#SBATCH --output=JOB.o

FILE=COO_at_$1

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# running
source /home/software/materia/intel/oneapi/setvars.sh --force
module load materia/qe/7.1_intel-oneapi
mpirun -n 56 pw.x -nk 1 -input $FILE.pwi > $FILE.pwo